#!/usr/sbin/nft -f

flush ruleset

define WAN_IF = "eth0"
define AWG_IF = "awg0"
define AWG_PORT = 32304
define AWG_NET = 10.0.1.0/24

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state established,related accept
        ct state invalid drop
        iifname "lo" accept
        tcp dport 22 accept
        udp dport $AWG_PORT accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
        iifname $AWG_IF oifname $WAN_IF accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table inet nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr $AWG_NET oifname $WAN_IF masquerade
    }
}